services:
  mongo:
    image: mongo:7
    container_name: ocean-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ocean_view_resort
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./api
    container_name: ocean-api
    env_file:
      - ./api/.env
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
      mailhog:
        condition: service_started

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ocean-mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # UI port

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
    container_name: ocean-frontend
    ports:
      - "3000:3000"

  mongo-express:
    image: mongo-express:latest
    container_name: ocean-db-viewer
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
