spring.application.name=ocean-view-resort

spring.data.mongodb.uri=mongodb+srv://root:0kZwLySjgLKQyICE@cluster0.pin3l.mongodb.net/ocean_view_resort

app.jwt.issuer=ocean-view-resort
app.jwt.secret=${JWT_SECRET:change-this-secret}
app.jwt.expiration=3600000
