spring.application.name=ocean-view-resort

spring.data.mongodb.uri=mongodb+srv://root:0kZwLySjgLKQyICE@cluster0.pin3l.mongodb.net/ocean_view_resort

app.jwt.issuer=ocean-view-resort
app.jwt.secret=${JWT_SECRET:93bfcfca326f240318b5d576442ed019}
app.jwt.expiration=3600000

app.seed.enabled=${APP_SEED_ENABLED:true}
app.seed.default-password=${SEED_DEFAULT_PASSWORD:Password@123}
